### ISSUE TITLE
Doesn't include com.sun.net.httpserver package?

### ISSUE THREAD

**Issue by kevinresol** [HaxeFoundation/hxjava#21]
From Java SE6, there is a built-in HttpServer class in the package com.sun.net.httpserver, but unable to reference it in hxjava. I think it is needed to update the included jar, but have no idea how to do so.

**Comment by kevinresol** [comment]
The class exists by default, which can be verified by the following code:

```haxe

class Server {
	static function main() {
		trace(HttpServer); // it can print out
	}
}

@:native('com.sun.net.httpserver.HttpServer')
extern class HttpServer {}
```

**Comment by dmitryhryppa** [comment]
Oh, `com.sun.*` package has been added since the latest updates of hxjava (5ba638f05ce7192c6f635d8082ab319a81d38af4)
So, HttpSever is now available for use.

**Comment by nadako** [comment]
Thanks!

**Comment by Simn** [comment]
Reopening because the package has been removed again. Not sure what to do with this, but I don't think we should have this stuff in the default completion.

**Comment by Simn** [comment]
And closing again because I reverted the revert.

**Comment by dmitryhryppa** [comment]
> And closing again because I reverted the revert.

Looks like you forgot to press the close button for this issue. Just to let you know :)
