### ISSUE TITLE
[Feature request] Update hxjava-std.jar

### ISSUE THREAD

**Issue by Grabli66** [HaxeFoundation/hxjava#23]
Current hxjava-std.jar is six years old and does not have a lot of classes.
I think classes can be taken from openjdk-8

**Comment by Simn** [comment]
I agree we should update this for Haxe 4. Does anyone feel responsible?

**Comment by nadako** [comment]
@waneck is the `hxjava-std.jar` just a renamed `rt.jar` from the `lib` directory of JRE?
