### ISSUE TITLE
NPE when using Type.createInstance and null constructor params

### ISSUE THREAD

**Issue by ianharrigan** [HaxeFoundation/hxjava#24]
Hi there,

So there is an issue currently in hxJava whereby if you try to pass a `null` value as a constructor param it causes an NPE and the whole app crashes. eg:

```haxe
Type.createInstance(SomeClass, [1, null, 2]);
``` 

This is because the code in Type.java attempts to get the class from the params passed, one of which is `null`

Extract from Type.java:

```java
Object o = args.__get(i);
objs[i]= o;
cls[i] = o.getClass(); // <--------------- this is the issue
boolean isNum = false;
```

I had a quick go at patching it and its a little more involved than i originally assumed (hence no PR).

Cheers,
Ian

**Comment by Gama11** [comment]
Considering Java's `Type.createInstance` implementation not here but [in the Haxe repo](https://github.com/HaxeFoundation/haxe/blob/development/std/java/_std/Type.hx), it's probably better to report it there?

**Comment by ianharrigan** [comment]
Right fair enough - makes sense.

**Comment by RealyUniqueName** [comment]
See https://github.com/HaxeFoundation/haxe/issues/7505

**Comment by markknol** [comment]
(Note sure if you are aware, but we can transfer issues across our GitHub organisation  )
![image](https://user-images.githubusercontent.com/576184/70698979-b5f52400-1cc8-11ea-8822-f147667bb390.png)

**Comment by Gama11** [comment]
Not back when this issue was created, I think. :)

**Comment by markknol** [comment]
Oops, was only looking at date of latest comment 😛
