### ISSUE TITLE
hxjava-std.lib update

### ISSUE THREAD

**Issue by Simn** [HaxeFoundation/hxjava#27]
I have just reverted https://github.com/HaxeFoundation/hxjava/pull/25 with a force-push to avoid having the file in the git history. I checked the previous version and found that it had the `Code` attributes stripped, which greatly decreases the file size. Since we don't need this information, we should do this for the updated version as well.

There's probably some tool to do that, but I'm not very familiar with Java tooling. If anyone has some knowledge here, please share it.

**Comment by nadako** [comment]
Oh, so what we had is a signature-only version without the actual bytecode? That's nice, we should do that with the new version!

**Comment by dmitryhryppa** [comment]
What about @nadako proposal about using `rt.jar` from Java installation directory instead of keeping it directly in hxjava repo?
That's opening possibilities to use any version of Java you need, not just Java 8.

**Comment by Simn** [comment]
This issue is about the file being unnecessarily big, using it from a different source wouldn't help.
